# Generated by Django 4.1 on 2022-08-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quilt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=2048)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LARGE_WORKS", "Large Works"),
                            ("SMALL_WORKS", "Small Works"),
                            ("PORTRAITS", "Portraits"),
                            ("PEOPLE", "People"),
                            ("NUDES", "Nudes"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FOR_SALE", "For Sale"),
                            ("NOT_FOR_SALE", "Not for Sale"),
                            ("PRIVATE_COLLECTION", "In a Private Collection"),
                            ("TOURING_EXHIBITION", "In a Touring Exhibition"),
                        ],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
