# Generated by Django 4.1 on 2022-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quilts", "0003_alter_quilt_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="quilt",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
